spring.application.name=CineClub
spring.datasource.url=jdbc:postgresql://${HOST_DB}/mydatabase-cineClub
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=muriel
spring.security.user.password=1234

PRE_SCREENING_THRESHOLD=15
USER_HOLD_LIMIT=4
HOLD_TTL_DEFAULT=300