spring.application.name=CineClub
spring.datasource.url=jdbc:postgresql://${HOST_DB}/mydatabase-cineClub
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=muriel
spring.security.user.password=${PASSWORD_SE}